global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'eventura'
    static_configs:
      - targets: ['host.docker.internal:5001']
    scrape_interval: 30s
    metrics_path: /metrics
    basic_auth:
      username: prom-user
      password: DtU9It1v2Lt6c00e8s2dRe1JOC

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    basic_auth:
      username: prom-user
      password: DtU9It1v2Lt6c00e8s2dRe1JOC